log:
  enable: true
  level: info

server:
  hosts: []
  ports: []
  enabled: []
  endpoints: []
  labels: {}
  port_map: {}
  tags_by_service: {}
  services: {}
  advanced:
    tags: []
    config: {}
    backends: []
